import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import {getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import {getFirestore,doc,getDocFromServer,setDoc,writeBatch,serverTimestamp,runTransaction} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';
import {parseSheet,splitChunks} from './import-core.js';
const app=initializeApp({apiKey:'AIzaSyC_5NL_lioKb869HMYwQXkrY5tMI-zf0jA',authDomain:'consulta-dev.firebaseapp.com',projectId:'consulta-dev',storageBucket:'consulta-dev.firebasestorage.app',messagingSenderId:'833424717922',appId:'1:833424717922:web:6a2e03ebe6c717a9f6793b'});
const auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id),meta=doc(db,'dev_meta','active');
let headers=[],candidate=null,baseline=null,busy=false,allowed=false,ready=false;
const status=(s)=>{$('adminstatus').textContent=s};
const error=e=>({'auth/invalid-credential':'E-mail ou senha incorretos.','auth/operation-not-allowed':'Ative o login por e-mail e senha no Firebase.','auth/unauthorized-domain':'Autorize este domínio no Firebase Authentication.','permission-denied':'Acesso não autorizado. Confira as regras e a autorização do importador.','auth/too-many-requests':'Muitas tentativas. Aguarde antes de tentar novamente.'}[e.code]||'Não foi possível concluir. Confira a conexão e a configuração do Firebase. Código: '+(e.code||e.message));
$('adminopen').onclick=()=>$('admin').showModal();$('adminclose').onclick=()=>{if(!busy)$('admin').close()};$('admin').addEventListener('cancel',e=>{if(busy)e.preventDefault()});
$('loginform').onsubmit=async e=>{e.preventDefault();status('Entrando…');try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);$('password').value=''}catch(e){status(error(e))}};
$('logout').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{allowed=false;candidate=null;$('publish').disabled=true;$('file').value='';$('review').textContent='';$('importarea').hidden=true;$('loginform').hidden=!!user;if(!user){status('');return}try{const permission=await getDocFromServer(doc(db,'dev_importers',user.uid));allowed=permission.exists()&&permission.data().enabled===true;$('importarea').hidden=false;$('file').disabled=!allowed;$('account').textContent=user.email;status(allowed?'Selecione a base completa para conferir.':'Sua conta não tem permissão para importar. Solicite a liberação ao administrador.')}catch(e){$('importarea').hidden=false;$('file').disabled=true;status(error(e))}});
async function sheetJS(){if(window.XLSX)return window.XLSX;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js';s.onload=resolve;s.onerror=()=>reject(Error('Biblioteca Excel indisponível'));document.head.append(s)});return window.XLSX}
async function load(){try{headers=await fetch('./schema.json').then(r=>{if(!r.ok)throw Error('Schema');return r.json()});const snap=await getDocFromServer(meta);if(!snap.exists()){window.startApp({headers,rows:[]});ready=true;$('baseinfo').textContent='Sem base publicada';$('cloudstatus').textContent='Nenhuma base publicada. Use Atualizar base para fazer a primeira importação.';return}const m=snap.data();if(!Number.isInteger(m.chunks)||m.chunks<1||m.chunks>1000)throw Error('Manifesto inválido');const rows=[];for(let offset=0;offset<m.chunks;offset+=8){const part=await Promise.all(Array.from({length:Math.min(8,m.chunks-offset)},(_,j)=>getDocFromServer(doc(db,'dev_versions',m.version,'chunks',String(offset+j)))));for(const chunk of part){if(!chunk.exists())throw Error('Base incompleta');rows.push(...JSON.parse(chunk.data().payload))}}if(rows.length!==m.count)throw Error('Contagem divergente');window.startApp({headers,rows});ready=true;$('baseinfo').textContent='Atualizada em '+(m.publishedAt?.toDate().toLocaleString('pt-BR')||'data não informada');$('cloudstatus').textContent=rows.length.toLocaleString('pt-BR')+' registros · '+m.filename+' · Atualize a página para buscar uma nova publicação.'}catch(e){$('baseinfo').textContent='Base indisponível';$('cloudstatus').textContent=error(e)+' Atualize a página para tentar novamente.'}}load();
$('file').onchange=async()=>{candidate=null;$('publish').disabled=true;$('review').textContent='';const file=$('file').files[0];if(!file)return;if(!allowed)return status('Importação não autorizada.');if(file.size>20*1024*1024)return status('A planilha deve ter até 20 MB.');status('Lendo e conferindo a planilha…');try{if(!headers.length)throw Error('Aguarde o carregamento da configuração.');const XLSX=await sheetJS(),wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const name=wb.SheetNames.includes('Planilha1')?'Planilha1':wb.SheetNames.length===1?wb.SheetNames[0]:null;if(!name)throw Error('Use uma aba chamada Planilha1 ou um arquivo com uma única aba.');const parsed=parseSheet(XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null,raw:true}),headers);const snap=await getDocFromServer(meta);baseline=snap.exists()?snap.data().version:null;candidate={...parsed,filename:file.name};$('review').textContent=`${parsed.rows.length.toLocaleString('pt-BR')} registros. Valor das notas: ${(parsed.total/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}. Pagamentos informados: ${(parsed.paid/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}. ${parsed.duplicates} registros com chave repetida, preservados. ${parsed.numericKeys} chaves vieram numéricas no Excel e podem ter perdido dígitos na origem; confira o arquivo. ${parsed.divergences} pagamentos com status diferente de Lançada. A base atual (${snap.exists()?snap.data().count:0} registros) será substituída integralmente.`;$('publish').disabled=false;status('Confira o resumo e clique em Publicar base conferida.')}catch(e){candidate=null;status(e.message)}};
$('publish').onclick=async()=>{if(!candidate||!allowed||busy)return;busy=true;$('publish').disabled=true;$('file').disabled=true;$('logout').disabled=true;try{const version=crypto.randomUUID(),chunks=splitChunks(candidate.rows);await setDoc(doc(db,'dev_versions',version),{createdAt:serverTimestamp(),createdBy:auth.currentUser.uid,filename:candidate.filename,count:candidate.rows.length,chunks:chunks.length});for(let offset=0;offset<chunks.length;offset+=20){const batch=writeBatch(db);chunks.slice(offset,offset+20).forEach((payload,j)=>batch.set(doc(db,'dev_versions',version,'chunks',String(offset+j)),{payload}));await batch.commit();status(`Carregando ${Math.min(offset+20,chunks.length)} de ${chunks.length} partes…`)}await runTransaction(db,async tx=>{const current=await tx.get(meta);if((current.exists()?current.data().version:null)!==baseline)throw Error('Outra pessoa atualizou a base. Selecione a planilha novamente para conferir a versão atual.');tx.set(meta,{version,chunks:chunks.length,count:candidate.rows.length,filename:candidate.filename,publishedAt:serverTimestamp()})});candidate=null;status('Base publicada. Recarregando a consulta…');location.reload()}catch(e){status(error(e)+' A base anterior continua publicada.');$('publish').disabled=!candidate}finally{busy=false;$('file').disabled=!allowed;$('logout').disabled=false}};
window.addEventListener('beforeunload',e=>{if(busy){e.preventDefault();e.returnValue=''}});

